import = [
  "~/.local/share/nvim/site/pack/packer/start/zenbones.nvim/extras/alacritty/zenbones_dark.toml"
]

[font]
size = 16

[font.bold]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"
