#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $DIR

if [ ! -d "$HOME/.vim" ]; then
  ln -s "$DIR/vim" ~/.vim
fi

if [ ! -f "$HOME/.vimrc" ]; then
  ln -s "$DIR/vim/vimrc" ~/.vimrc
fi

if [ ! -f "$HOME/.tmux.conf" ]; then
  ln -s "$DIR/tmux.conf" ~/.tmux.conf
fi

if [ ! -d "vim/bundle/Vundle.vim" ]; then
  cd "$DIR/vim/bundle" && git clone git@github.com:VundleVim/Vundle.vim.git
fi

echo ". ~/dot-files/bashrc" >> ~/.bashrc
