[colors.primary]
background = "0x2c2e34"
foreground = "0xe2e2e3"

[colors.normal]
black = "0x181819"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[colors.bright]
black = "0x7f8490"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"
