[colors.primary]
background = "0x2d2a2e"
foreground = "0xfcfcfa"

[colors.normal]
black = "0x19181a"
red = "0xff6188"
green = "0xa9dc76"
yellow = "0xffd866"
blue = "0xfc9867"
magenta = "0xab9df2"
cyan = "0x78dce8"
white = "0xfcfcfa"

[colors.bright]
black = "0x19181a"
red = "0xff6188"
green = "0xa9dc76"
yellow = "0xffd866"
blue = "0xfc9867"
magenta = "0xab9df2"
cyan = "0x78dce8"
white = "0xfcfcfa"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"
