# Configure SSH Agent to start automatically
eval "$(ssh-agent -s)" > /dev/null
ssh-add --apple-use-keychain > /dev/null 2>&1

[[ -f /usr/local/share/chruby/chruby.sh ]] && source /usr/local/share/chruby/chruby.sh
[[ -f /usr/local/share/chruby/auto.sh ]] && source /usr/local/share/chruby/auto.sh

[[ -f /opt/homebrew/opt/chruby/share/chruby/chruby.sh ]] && source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
[[ -f /opt/homebrew/opt/chruby/share/chruby/auto.sh ]] && source /opt/homebrew/opt/chruby/share/chruby/auto.sh

[[ -f ~/dotfiles/config/secrets.sh ]] && source ~/dotfiles/config/secrets.sh

chruby_auto

# Variables
export EDITOR=nvim
export GPG_TTY=$(tty)
export NO_COVERAGE=true
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PATH="$HOME/bin/nvim-macos/bin:/usr/local/bin:/opt/homebrew/bin:$PATH:$HOME/bin:/usr/local/opt/python@3.10/libexec/bin:/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export SWAGGER_DRY_RUN=0

export SHELL=zsh
export NODE_OPTIONS="--no-warnings"

# Default schema compatibility for Avro registry
# https://github.com/salsify/avro-schema-registry/blob/f2da75508bea91611f0a1c99a3b46259e5197cc0/config/application.rb#L49
export DEFAULT_COMPATIBILITY="FORWARD"

# Aliases
alias be="bundle exec"
alias dc="docker-compose"
alias dotfiles="cd ~/dotfiles"
alias vim="nvim"
alias ch="cd ~/code/charlotte"
alias dr="cd ~/code/dreamatorium"
alias tc="cd ~/code/telchar"
alias po="cd ~/code/porter"
alias pair="tmux -2 new -s pairing"
alias pair_with_ben="upterm host --github-user BenKanouse --force-command 'tmux attach -t pair-programming' -- tmux new -t pair-programming"
alias pair_with_rob="upterm host --github-user jonesdeini --force-command 'tmux attach -t pair-programming' -- tmux new -t pair-programming"
alias python="/usr/local/bin/python3"

alias rebasedevelop="git co develop && git fetch && git rebase && git co - && git rebase develop"

setopt nosharehistory # Do not share history between ZSH instances

# Make Tmux resize correctly when pairing
if [ -n "$TMUX" ]; then
  tmux set window-size smallest
fi

# Render thinner font
defaults write -g AppleFontSmoothing -int 0
